#!/bin/sh
#
# Automatically checks for dumps

VAR=$(git diff --cached | grep -wiE "var_dump|dump|die|dd")
if [ ! -z "$VAR" ]; then
  echo "You've left a var_dump(), dump(), dd(), or die() in one of your files. Aborting commit..."
  exit 1
fi
